module.exports={

ADMIN_COLLECTION:'admin',
HOTELUSER_COLLECTION:'hotel',
USER_COLLECTION:'user',
CITY_COLLECTION:'city',
ROOM_COLLECTION:'room',
ROOMDATA_COLLECTION:'roomdata',
ROOMBOOKING_COLLECTION:'bookedroom'

}