module.exports={

ADMIN_COLLECTION:'admin',
HOTELUSER_COLLECTION:'hotel',
USER_COLLECTION:'user',
CITY_COLLECTION:'city',
ROOM_COLLECTION:'room',
ROOMDATA_COLLECTION:'roomdata',
ROOMBOOKING_COLLECTION:'bookedroom',
PENALTYPAY_COLLECTION:'PENALTYPAY',
PENALTY_COLLECTION:'penalty',
RETURNPAY_COLLECTION:'return',
REVIEW_COLLECTION:'reviews',
CONFBOOKING_COLLECTION:'booked'

}